require("prototypes/item-group")
require("prototypes/item")
require("prototypes/recipe")
require("prototypes/technology")
require("prototypes/tips")
require("prototypes/resources")
require("prototypes/entity/entity")
require("prototypes/planet/planet")